# -*- mode: ruby -*-
# vi: set ft=ruby :

# Use the latest vagrant, at least as of 2023-07-13.
Vagrant.require_version ">= 2.3.7"

Vagrant.configure("2") do |config|
  #-- plugin config ------------------------------------------------------------
  config.vagrant.plugins = ["vagrant-sshfs"]
  config.vm.synced_folder ".", "/vagrant", type: "sshfs"

  #-- guest vm config ----------------------------------------------------------
  config.vm.box = "generic/centos9s"
  config.vm.define :centos9s do |box|
    box.vm.host_name = "centos9s"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs"
    box.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.cpus = 2
      # If you don't set this, you get screen flicker and "Invalid settings detected" in the GUI.
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    box.vm.provision "shell", privileged: false, inline: <<~'SHELL'
      echo 'Hello, world!'
    SHELL
  end
end
