Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.define :centos8s do |box|
    box.vm.host_name = "centos8s"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs"
    box.vm.provider :virtualbox do |v|
      v.memory = 8192
      v.cpus = 4
    end
    box.ssh.insert_key = false
    #box.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    box.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
    box.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      sudo /vagrant/install-dev-tools.sh
      sudo /vagrant/install-docker.sh
    SHELL
  end
end
