Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"
  config.vm.define :awscli do |box|
    box.vm.host_name = "awscli"
    box.vm.network "private_network", type: "dhcp"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs = 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      sudo dnf -y -q install python3 unzip
      cd /tmp
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      /usr/local/bin/aws --version
    SHELL
  end
end
