Vagrant.configure("2") do |config|

  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"

  # NOTE:  If you need to change the IP address for your vagrant environment:
  #            grep -F '192.168.' *.sh
  #        ...to find the IPs in use, and adjust as necessary.
  config.vm.define :centos8a do |box|
    box.vm.host_name = "centos8a"
    box.vm.network "private_network", ip: "192.168.56.20"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs = 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      cd /vagrant
      sudo ./00-pre-flight.sh
      ./01-create-ssh-cert-examples.sh
      sudo ./02-sign-this-hosts-sshd-keys.sh
    SHELL
  end

  config.vm.define :centos8b do |box|
    box.vm.host_name = "centos8b"
    box.vm.network "private_network", ip: "192.168.56.21"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs = 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      cd /vagrant
      sudo ./00-pre-flight.sh
      sudo ./02-sign-this-hosts-sshd-keys.sh
      ./03-client-test.sh
      SHELL
  end

end
