Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "ubuntu2004" do |box|
    box.vm.host_name = "ubuntu2004"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs for 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      echo 'TEST MESSAGE:  Yay!  It worked!'
    SHELL
  end
end
