# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/36-cloud-base"
  config.vm.box_version = "36-20220504.1"
  config.vm.define :fedora36 do |guest|
    guest.vm.host_name = "fedora36"
    guest.vm.network "forwarded_port", guest: 3389, host: 3389
    guest.vm.provider :virtualbox do |v|
      v.memory = 8192
      v.cpus = 2
    end
    guest.vm.provision :shell do |shell|

      # IMPORTANT:  Run as non-root user, and `sudo` what you must.  This is
      # needed for user-land things, like gnome sessions, the keyring, etc.
      shell.privileged = false

      shell.inline = <<~'SHELL'

        # NOTE:  Update the OS _before_ you try to install a desktop. There are
        # too many packages needed by a desktop, and the mismatch between what's
        # currently running and what's needed can cause weird runtime issues and
        # instability.
        sudo dnf clean all
        sudo dnf -y update

        # Install a desktop
        sudo dnf -y group install workstation-product-environment
        sudo cp -a /etc/gdm/custom.conf{,.orig}
        sudo tee /etc/gdm/custom.conf << 'EOF'
        [daemon]
        WaylandEnable=false
        DefaultSession=gnome-xorg.desktop
        AutomaticLoginEnable=True
        AutomaticLogin=vagrant
        EOF
        sudo systemctl set-default graphical.target

        # firewall (disabled by default, but just in case)
        sudo firewall-cmd --permanent --add-service=rdp
        sudo firewall-cmd --reload

        # misc
        sudo dnf -y install vim

      SHELL

      shell.reboot = true

    end
  end
end

