# -*- mode: ruby -*-
# vi: set ft=ruby :

# Use the latest vagrant, at least as of 2022-07-22.
Vagrant.require_version ">= 2.2.19"

Vagrant.configure("2") do |config|
  #-- plugin config ------------------------------------------------------------
  config.vagrant.plugins = ["vagrant-sshfs"]

  #-- guest vm config ----------------------------------------------------------
  config.vm.define "ubuntu2204" do |guest|
    guest.vm.box = "ubuntu/jammy64"
    guest.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus   = "2"
      # If you don't set this, you get "Invalid settings detected" in the GUI.
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    guest.vm.synced_folder ".", "/vagrant", type: "sshfs"
  end
end
