Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"
  config.vm.define "docker" do |box|
    box.vm.host_name = "docker"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs = 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 8192
      v.cpus = 4
    end
    box.vm.provision "shell", privileged: true, path: "install.sh"
  end
end
