# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ----- Red Hat Ansible Tower ------------------------------------------------
  config.vm.define :tower do |box|
    box.vm.box = "ansible/tower"
    box.vm.box_version = "3.8.5"
    box.vm.host_name = "tower"
    box.vm.network "forwarded_port", guest:  443, host: 8443
    box.vm.network "forwarded_port", guest: 3389, host: 3389
    box.vm.provider :virtualbox do |vb|
      vb.memory = 8192
      vb.cpus = 2
    end
    # NOTE:  You'll need `vagrant plugin install vagrant-sshfs` to 2-way sync
    #   this directory with /vagrant in the VM.  It's helpful for development
    #   in general, but it's necessary for the demo.
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # for 2-way sync
    box.vm.provision "shell", path: "Vagrant-provision-tower.sh"
  end
  
  # ----- Ansible client for demo/dev ------------------------------------------
  config.vm.define "ansible" do |box|
    box.vm.box = "centos/stream8"
    box.vm.box_version = "20210210.0"
    box.vm.host_name = "ansible"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # for 2-way sync
    box.vm.provision "shell", path: "Vagrant-provision-ansible.sh"
  end
end
