Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"
  config.vbguest.installer_options = { allow_kernel_upgrade: true } # for vagrant-vbguest plugin
  config.vm.define :centos_stream_8 do |box|
    box.vm.host_name = "centos-stream-8"
    #box.vm.network "private_network", type: "dhcp"
    box.vm.network "private_network", ip: "192.168.56.20"
    #box.vm.network "forwarded_port", guest: 80,  host: 8080
    #box.vm.network "forwarded_port", guest: 443, host: 8443
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs = 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      echo 'TEST MESSAGE:  Yay!  It worked!'
    SHELL
  end

end
