---
- name: Jinja example
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Cleaning up previous output.txt
      ansible.builtin.file:
        path: output.txt
        state: absent

    - name: Gather some basic details about localhost
      ansible.builtin.setup:
        gather_subset:
          - 'min'

    - name: Show the ansible date and time fact object
      ansible.builtin.debug:
        var: ansible_facts.date_time

    - name: Write the output file using a template
      ansible.builtin.template:
        src: template.j2
        dest: output.txt
