Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.1"
  config.vm.define :centos_7 do |box|
    box.vm.host_name = "centos-7"
    box.vm.network "private_network", type: "dhcp"
    box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs = 2-way sync
    box.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      echo 'TEST MESSAGE:  Yay!  It worked!'
    SHELL
  end
end
