# -*- mode: ruby -*-
# vi: set ft=ruby :

# Accessing the RHEL package repositories requires registration (via
# `subscription-manager`).  Otherwise, DNF commands will fail due to
# authentication.  The `vagrant-registration` plugin helps with automating this
# process.  Copy `.env.sample.txt` to `.env` and update it with your
# credentials:
#
#     cp .env.sample.txt .env
#     vim .env
#
# However, if you have to perform this manually on the guest VM for some reason,
# this is the equivalent:
#
#     subscription-manager register --auto-attach --force
#
# A Red Hat username and password (or an organization and activation key) is
# required.  For lab and development purposes, you can register for a no-cost
# account at:  https://developers.redhat.com/

# Use the latest vagrant, at least as of 2024-10-17.
Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
  #-- plugin config ------------------------------------------------------------
  config.vagrant.plugins = ["vagrant-libvirt", "vagrant-registration", "vagrant-env", "vagrant-sshfs"]
  config.env.enable
  config.registration.username = ENV['RED_HAT_SUBSCRIPTION_MGR_USER']
  config.registration.password = ENV['RED_HAT_SUBSCRIPTION_MGR_PASS']
  config.vm.synced_folder ".", "/vagrant", type: "sshfs"

  #-- guest vm config ----------------------------------------------------------
  config.vm.define "rhel8" do |guest|
    guest.vm.box = "generic/rhel8"
    # guest.vm.network "forwarded_port", guest: 9090, host: 9090 # cockpit
    guest.vm.provider :libvirt do |lv|
      lv.memory = "4096"
      lv.cpus   = "2"
    end
    guest.vm.provision "shell", privileged: false, inline: <<-SHELL
      # sudo dnf -y install cockpit
      # sudo systemctl enable --now cockpit.socket
      echo 'Hello, world!'
    SHELL
  end
end
