Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20220308.0.0"
  config.vm.define "ubuntu2004" do |box|
    box.vm.host_name = "ubuntu2004"
    box.vm.network "private_network", type: "dhcp"
    box.vm.network "forwarded_port", guest: 3389,  host: 3389
    box.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 2
    end
    box.vm.provision "shell", privileged: true, inline: <<~'SHELL'
      echo 'TEST MESSAGE:  Yay!  It worked!'
    SHELL
  end
end
