Vagrant.configure("2") do |config|

  config.vm.box = "fedora/34-cloud-base"
  config.vm.box_version = "34.20210423.0"

	# config.vm.network "forwarded_port", guest: 80,  host: 8080
	# config.vm.network "forwarded_port", guest: 443, host: 8443
	# config.vm.network "private_network", ip: "192.168.56.10"
	# config.vm.provision "shell", privileged: true, inline: <<~'SHELL'
	# 	cp -rf /vagrant /srv/mirror
	# 	/srv/mirror/install.sh
	# SHELL
  #v.nested = true
  #v.disk_driver :cache => 'none'

  # runs minikube and awx-operator to install/run awx
  config.vm.define :awx do |srv|
    srv.vm.host_name = "awx"
	  srv.vm.network "private_network", ip: "192.168.56.10"
	  srv.vm.network "forwarded_port", guest: 80,  host: 8080
	  srv.vm.network "forwarded_port", guest: 443, host: 8443
    srv.vm.provider :virtualbox do |v|
      v.memory = 8192
      v.cpus = 4
    end
  end

  # example system to manage, use as bastion host to troubleshoot, etc
  config.vm.define :server01 do |srv|
    srv.vm.host_name = "server01"
    srv.vm.network "private_network", ip: "192.168.56.11"
    srv.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

end

