Vagrant.configure("2") do |config|
    if Vagrant.has_plugin? "vagrant-vbguest"
      config.vbguest.auto_update = false
      config.vbguest.no_remote   = true
    end
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20220308.0.0"
    config.vm.define "ubuntu2004" do |box|
      box.vm.network "forwarded_port", guest: 8000, host: 8000
      if Vagrant.has_plugin? "vagrant-sshfs"
        box.vm.synced_folder ".", "/vagrant", type: "sshfs" # sshfs for 2-way sync
      end
      box.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 2
      end
      box.vm.provision "shell", path: "install-mkdocs.sh"
    end
  end
  