# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-sshfs", "vagrant-reload"]
  config.vm.box = "centos/stream8"
  config.vm.define "conjur" do |generic|
    generic.vm.host_name = "docker"
    generic.vm.synced_folder ".", "/vagrant", type: "sshfs"
    generic.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 2
    end
    generic.vm.provision "shell", privileged: true,  path: "install-docker.sh"
    #generic.vm.provision "shell", privileged: true,  inline: "dnf update -y"
    generic.vm.provision "reload"
    generic.vm.provision "shell", privileged: false, path: "install-conjur.sh"
    generic.vm.provision "shell", privileged: false, path: "install-ansible.sh"
  end
end
